### ISSUE TITLE
Layout shifts on hover

### ISSUE THREAD

**Issue by m-i-l** [searchmysite/searchmysite.net#113]
The change in font weights on hover can introduce layout shifts, i.e. cause parts of the page to jump. See video a user has kindly prepared to illustrate:

https://github.com/searchmysite/searchmysite.net/assets/12760482/2928f6fb-672c-47cf-829f-0e67947b02f0

**Comment by extua** [comment]
This looks like it's caused by the two `.sms-results-list h2.sms-h2 a:hover` rules in letterpress.css here

https://github.com/searchmysite/searchmysite.net/blob/d752fdc1dc6cd0f12902d1f3a49241f5a350b8e0/src/web/content/static/css/letterpress.css#L612C1-L612C38

When you hover over the h2 element, it sets the border to none, triggering the layout shift.

You could get rid of that rule, but would it cause problems elsewhere?

**Comment by squalx** [comment]
Good catch @extua. Thanks for the possible solution. I'll take a look as soon as I can.

If you want you can submit a fix. Me and @m-i-l can check that nothing else breaks and do workarounds accordingly. I'm just not sure what the process is for that. You can ask @m-i-l if interested. Otherwise I'll try to get to this on the weekend.

**Comment by extua** [comment]
Thanks @squalx, I've started off a pull request at #115 to take out the `border: none` rule.

**Comment by m-i-l** [comment]
Many thanks for your fix - now released in v1.4.1.

**Comment by squalx** [comment]
Thanks @extua ! Your help is very much appreciated.
