### ISSUE TITLE
Search: Provide OpenSearch Atom responses for standards-based federation

### ISSUE THREAD

**Issue by alcinnz** [searchmysite/searchmysite.net#26]
I notice you have an [OpenSearch document](https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md), as it's a standard I've long been interested in for enabling federated websearch.

What do you think of delivering search results [in RSS or Atom feeds](https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md#opensearch-response-elements) for clients to combine with other compatable search engines (currently mostly government open data sites)?

I'd be willing to contribute the code or develop a client.

**Comment by m-i-l** [comment]
Many thanks for your suggestion and offer of help. Do you have a specific use case in mind for the OpenSearch feed? Is there an app or site you think would benefit from a feed from searchmysite.net?

Or are you thinking more about the idea of different searchmysite instances talking to each other? I did have some notes on that in the post at https://blog.searchmysite.net/posts/searchmysite.net-is-now-open-source/ . In short, an API based approach would most likely lead to separate results lists or a single not very well integrated results list, so a lower level integration would be better for the users. That's not to say the API based approach shouldn't be implemented as an initial solution though, with the lower level integration at a (much) later date.

Note also that there is a site-specific API already, e.g. https://searchmysite.net/api/v1/search/michael-lewis.com?q=* for my site. It is one of the features enabled by the verified listing (although I have been wondering if it should be enabled by default so people could try out the API before verifying ownership of their site). There hasn't been as much interest in the API as I thought there would be so far to be honest though.

**Comment by alcinnz** [comment]
I'm wanting to build a client which combines search results from multiple compatible search engines, like Searx does on a site-by-site basis. Yes there's important data I'd require from search results, including, most challengingly, ranking numbers! Which is included in the OpenSearch spec.

So far I've seen [GeoNetwork](https://geonetwork-opensource.org/) & I think [CKAN](https://ckan.org/) support enough of OpenSearch for me to build such a client.

**Comment by m-i-l** [comment]
Okay. Sounds interesting.

In my experience, it'll be difficult to get sufficiently comparable scores from different engines to allow a combined results list. If we're talking about different searchmysite.net instances, which use the same fields and scoring algorithm, it might be more likely, but even then if the different instances were indexing different types of content which may have more or less data in certain fields, or greater or less linking between pages, or other differences, you could still end up with some instances drowning out others, unless you did the merging at index time rather than query time. But you could always try, or simply show non-combined results lists though.

So how would you approach it? The current API uses [flask_restx](https://github.com/python-restx/flask-restx). The main attraction of that was that it auto-generated the Swagger docs, although that's currently broken (issue #27). It also gets you your API very little code, although that may make it a little tricker to follow. It does look like there is a convert_data_to_xml described at https://flask-restx.readthedocs.io/en/latest/api.html which might help you get the sort of data described at https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md#examples-of-opensearch-responses .

**Comment by alcinnz** [comment]
The [relevant spec extension](https://github.com/dewitt/opensearch/blob/master/mediawiki/Specifications/OpenSearch/Extensions/Relevance/1.0/Draft%201.wiki) suggests clamping to a range between 0-1.

But personally I think the best approach would be to find the range of scores for each search results page being merged, and scale them all to the same range. Outliers could still throw that approach off, but it's worth trying.

My whole motivation is I don't want browsers to have a single default search engine (or homepage, etc), I reckon that's just encouraging web centralization!

**Comment by m-i-l** [comment]
There's a worked example of Solr's scoring for searchmysite.net at https://blog.searchmysite.net/posts/relevancy-tuning-for-searchmysite.net/ . In that example the top score was 8.09684.

If you want all of Solr's scores in the 0 to 1 range, you could subclass the scoring algorithm itself, but I'd rather not do that because there may unforeseen complications, e.g. performance, so it would be better to use something on top that would only apply to this case, e.g. a Function Query.

You'd typically use something like tanh to get all values in the 0 to 1 range, although looking through the Function Queries (https://lucene.apache.org/solr/guide/8_7/function-queries.html) I'm not seeing tanh or an obvious alternative. There is a tanh function available in the Streaming Expressions (see https://lucene.apache.org/solr/guide/8_7/scalar-math.html ) though, although to be honest I've not used Streaming Expressions before.

**Comment by m-i-l** [comment]
All search results pages (including Newest Pages and Browse Sites) now have a web feed icon in the top middle next to the results count (in between the Filters and Sort by). Clicking this takes you to an OpenSearch Atom format feed for that query.

This can be used to provide useful functionality including:
- Subscribe to new posts about your favourite topics. For example, if you are interested in seeing new posts about Stable Diffusion, search for "stable diffusion" (with double-quotes), change Sort by to "Published date (newest first)", (optionally) set filters like Language and In web feed, then copy and paste the web feed link into your feed reader. 
- Create feeds for sites which don't provide feeds. For example, use Browse Sites to get to the site you want (use e.g. Sort by Domain if necessary), click the Domain link to return all results from that domain, set Filters and Sort by if necessary, and use the web feed link.
