### ISSUE TITLE
search_deb (Solr) and web_deb containers not running

### ISSUE THREAD

**Issue by squalx** [searchmysite/searchmysite.net#86]
Hello,

I can't get the dev server to run on MacOs. The build and up commands for docker-compose work fine. I get no errors. But I get this when I try and restart those servers from the Docker Dashboard.

web_dev
```
2023-01-18 20:50:28 httpd: Syntax error on line 204 of /usr/local/apache2/conf/httpd.conf: Cannot load /usr/local/lib/python3.7/dist-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-x86_64-linux-gnu.so into server: /usr/local/lib/python3.7/dist-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory
2023-01-18 20:55:33 httpd: Syntax error on line 204 of /usr/local/apache2/conf/httpd.conf: Cannot load /usr/local/lib/python3.7/dist-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-x86_64-linux-gnu.so into server: /usr/local/lib/python3.7/dist-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory
```

search_dev
```
2023-01-18 20:50:27 Executing /opt/docker-solr/scripts/solr-precreate content /opt/solr/server/solr/configsets/content
2023-01-18 20:50:27 Creating /var/solr/data
2023-01-18 20:57:54 Executing /opt/docker-solr/scripts/solr-precreate content /opt/solr/server/solr/configsets/content
2023-01-18 20:57:54 Creating /var/solr/data
2023-01-18 20:50:27 mkdir: cannot create directory ‘/var/solr/data’: Operation not permitted
2023-01-18 20:57:54 mkdir: cannot create directory ‘/var/solr/data’: Operation not permitted
```

Some permission issues in the container. Sorry, I'm not that good with docker. Some pointers would help me, so I can somehow set the right directory permissions in the container? Or maybe this is something missing in a script?

The only thing that I did differently is that `searchmysite.net` directory is not in a `projects` directory. But I just changed the paths for the commands.

Also, I'm working of a fork, but it has your latest changes. I'm working on a fork to do my layout changes and then I'll make a PR here.

Thanks!

**Comment by m-i-l** [comment]
The search and db containers on dev persist the data on your local file system, so you don't lose any data between code changes. This means they need to have write permissions to your local file system. The db container uses uid 70 (usually postgres) and group root and sets permissions itself, while the search container uses uid 8983 and group id 8983 but you'll need to set ownership first.

The web and indexing containers on dev actually read direct from the source code on your local fie system, so you can make code changes and test right away. They just need read access, and after a git clone the files are usually world readable so you don't normally need to do anything there.

It shouldn't matter that your searchmysite.net directory is not in a projects directory, as long as src and data are at the same level, because the paths in docker-compose.yml are relative, i.e. when you are inside src (where you run the docker-compose build and docker-compose up -d) it is looking for ../data/solrdata and ../data/sqldata for the search and db containers and ./web and ./indexing for the web and indexing containers.

The first issue looks like it hasn't built the mod_wsgi correctly. Did you see anything unusual during the build step, and if you do 
```
docker exec -it web_dev ls -l /usr/local/lib/python3.7/dist-packages/mod_wsgi/server/
```
what do you see? The Dockerfile uses httpd:2.4.50 as a base rather than the later versions of httpd so that it uses the Python 3.7.3 which psycopg2 needs, so you should see a python3.7 in the container's /usr/local/lib/, but most of the modules should be the latest versions available, e.g. you should see a mod_wsgi-4.9.4.dist-info, psycopg2-2.9.5.dist-info, Flask-2.2.2.dist-info etc. in /usr/local/lib/python3.7/dist-packages/ .

The second issue does look like a permissions issue. Did you remember to do the `sudo chown 8983:8983 data/solrdata` step (or Mac equivalent) from the https://github.com/searchmysite/searchmysite.net/blob/main/README.md? If you're not doing at the outset you'll need a chown -R to fix any existing files (although it might be best just to start again).

**Comment by squalx** [comment]
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/1785755/213581787-1a7b7a51-966a-46ab-bfe2-a31a031d51d8.png">

I'm looking into the other stuff, but this is the dashboard, in case it helps.

**Comment by m-i-l** [comment]
Unfortunately you won't be able to get directory listings from containers that aren't running. The data/solrdata directoy permissions look okay (as an aside, in this case 8983:8983 refers to the user id and group id, rather than the port mappings shown on the docker dashboard).

You're not by any chance running one of the newer Macs which have "Apple silicon" (i.e. arm64 instead of amd64) though? There do seem to be a number of issues with them. For example the web container uses python wheels to build mod-wsgi, and it sounds like this won't work on "Apple silicon" if the package maintainer hasn't provided pre-compiled wheels for arm64 - see e.g. https://pythonspeed.com/articles/docker-build-problems-mac/ . I think a workaround may be to go through an emulation layer via `export DOCKER_DEFAULT_PLATFORM=linux/amd64`, but I don't have a Mac to test this.

**Comment by squalx** [comment]
I can confirm it was an Apple Silicon issue.

It's working fine on Pop_OS 22.04. The only issue that I have to solve is that I had to use `sudo` for both build and docker-compose. This is a docker installation / configuration issue. Whenever I sort that one out I'll try and add the comment here. But if you want to close this feel free.

**Comment by m-i-l** [comment]
Great, thanks for confirming. I'll close this now.
